name: Counter Runner

on:
  workflow_dispatch:
   inputs:
     auth:
        description: 'USERNAME'
        required: true
        default: 'Github_Username'
jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
  
    - name: Initialization environment
      run: sudo apt-get update && sudo apt-get install -y python python3
    - name: Downloading source code
      run: git clone https://github.com/AKhilRaghav0/Git-Profile-Counter && cd Git-Profile-Counter && rm username.txt && echo ""AKhilRaghav0"" >> username.txt
      
    - name: Excecution
      run: python bot.py
